#ifndef HANDLERS_H_
#define HANDLERS_H_
void int_hdl0();
void int_hdl1();
void int_hdl2();
void int_hdl3();
void int_hdl4();
void int_hdl5();
void int_hdl6();
void int_hdl7();
void err_int_hdl8();
void int_hdl9();
void err_int_hdl10();
void err_int_hdl11();
void err_int_hdl12();
void err_int_hdl13();
void err_int_hdl14();
void int_hdl15();
void int_hdl16();
void err_int_hdl17();
void int_hdl18();
void int_hdl19();
void int_hdl20();
void int_hdl21();
void int_hdl22();
void int_hdl23();
void int_hdl24();
void int_hdl25();
void int_hdl26();
void int_hdl27();
void int_hdl28();
void int_hdl29();
void err_int_hdl30();
void int_hdl31();
void int_hdl32();
void int_hdl33();
void int_hdl128();
#endif
